version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: balance_service_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "db_user", "-d", "balance_service_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
    container_name: balance_service
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: db_user
      DB_PASSWORD: password123
      DB_NAME: balance_service_db
    ports:
      - "8080:8080"
    networks:
      - app_network

volumes:
  pgdata:

networks:
  app_network:
